language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python plot_maker.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
